services:
  mariadb:
    container_name: mariadb_container
    image: mariadb
    networks:
      - mired
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  php:
    container_name: php_contenedor
    image: php:apache
    networks:
      - mired
    volumes:
      - /home/public:/var/www/html
    ports:
      - "80:80"

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    networks:
      - mired
    environment:
      - PMA_HOST=${PMA_HOST}
    ports:
      - "8080:80"

networks:
  mired:
    external: true
    name: mired
