Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
     config.vm.network "public_network"
     config.vm.synced_folder "./", "/vagrant"
     config.vm.provision "shell", path: "provision.sh"
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    # config.vm.provider "virtualbox" do |vb|
    #   vb.memory = "1024"
    # end
  end